# Generated by Django 4.2.11 on 2024-04-02 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emil', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('mibile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2024, 4, 2))),
            ],
        ),
    ]
